- name: Ensure Keycloak maps variables file created
  template:
    src: "{{ role_path }}/templates/keycloak-auth/map.py.j2"
    dest: "{{ matrix_synapse_base_path }}/saml2_attribute_maps/map.py"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  
- name: Ensure matrix Keycloak files created
  template:
    src: "{{ role_path }}/templates/keycloak-auth/{{ item }}.j2"
    dest: "{{ matrix_synapse_config_dir_path }}/{{ item }}"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  with_items:
    - "idp.xml"
    - "sp_conf.py"
    - "key.pem"
    - "cert.pem"
    